kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: resource-access
rules:
  - apiGroups: ["*"]
    resources: ["pods", "deployments", "daemonsets"]
    verbs: ["get", "list", "delete", "create"]
