kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resource-access-binding
  namespace: default
subjects:
- kind: User
  name: "system:serviceaccount:default:default"
  apiGroup: ""
roleRef:
  kind: Role
  name: resource-access
  apiGroup: ""
